config/routes.rb
Rails.application.routes.draw do
  root 'auctions#index'
  post '/auctions/:auction_id/publish', to: 'transitions#create_publish', as: 'publish'
  post '/auctions/:auction_id/cancel', to: 'transitions#create_cancel', as: 'cancel'
  post '/auctions/:auction_id/met', to: 'transitions#create_met', as: 'met'
  post '/auctions/:auction_id/not-met', to: 'transitions#create_not_met', as: 'not_met'
  post '/auctions/:auction_id/win', to: 'transitions#create_win', as: 'win'
  post '/auctions/:auction_id/draft', to: 'transitions#create_draft', as: 'draft'

  resources :users, only: [:new, :create] do
    resources :bids, only: :index
  end
  resources :auctions, shallow: true do
    resources :bids
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  belongs_to :user
  has_many :bids, dependent: :destroy

  validates :title, presence: true
  validates :details, presence: true
  validates :date_ending, presence: true
  validates :reserve_price, presence: true

  include AASM

  aasm do
    state :draft, initial: true
    state :published
    state :reserve_met
    state :won
    state :cancelled
    state :reserve_not_met

    event :publish do
      transitions from: :draft, to: :published
    end

    event :met do
      transitions from: :published, to: :reserve_met
    end

    event :not_met do
      transitions from: :published, to: :reserve_not_met
    end

    event :win do
      transitions from: [:published, :reserve_met], to: :won
    end

    event :cancel do
      transitions from: [:draft, :published, :won], to: :cancelled
    end

    event :draft do
      transitions from: [:cancelled, :published], to: :draft
    end
  end

  def max_amount
    bids.max.amount
  end
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :auction
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :auctions, dependent: :nullify
  has_many :bids, dependent: :nullify

  before_validation :downcase_email

  validates :email, presence: true,
                    uniqueness: true,
                    format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def full_name
    "#{first_name} #{last_name}".strip.squeeze(' ').titleize
  end

  private

  def downcase_email
    email.downcase! if email.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user
    redirect_to new_session_path, notice: 'Please Log In.' unless user_signed_in?
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end
  helper_method :current_user
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :authenticate_user

  def index
    @auctions = Auction.order(title: :DESC)
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new auction_params
    @auction.user = current_user
    @auction.date_ending = params[:auction][:date_ending]
    if @auction.save
      redirect_to auction_path(@auction)
    else
      render :new
    end
  end

  def show
    @auction = Auction.find params[:id]
    @bid = Bid.new
    @bids = @auction.bids.order(amount: :DESC)
  end

  def edit
    @auction = Auction.find params[:id]
  end

  def update
    @auction = Auction.find params[:id]
    if @auction.update auction_params
      flash[:notice] = 'Auction updated'
      redirect_to @auction
    else
      flash.now[:alert] = 'Please see errors below!'
      render :edit
    end
  end

  def destroy
    @auction = Auction.find params[:id]
    @auction.destroy
    redirect_to auctions_path, notice: 'Auction deleted'
  end

  private

  def auction_params
    params.require(:auction).permit(:title, :details, :date_ending, :reserve_price)
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def index
    @bids = current_user.bids
  end

  def create
    @bids = Bid.order(amount: :DESC)
    @auction = Auction.find params[:auction_id]
    bid_params = params.require(:bid).permit(:amount)
    @bid = Bid.new bid_params
    @bid.user = current_user
    @bid.auction = @auction
    if @bid.save
      if @bid.amount > @auction.reserve_price
        if @auction.published? || @auction.reserve_not_met?
          @auction.update_attributes(aasm_state: 'reserve_met')
        elsif @auction.max_amount && @auction.date_ending > Time.current
          @auction.update_attributes(aasm_state: 'won')
        end
      end
      redirect_to auction_path(@auction)
    else
      render 'auctions/show'
    end
  end
end

app/controllers/cancels_controller.rb
class CancelsController < ApplicationController
  def create
    auction = Auction.find params[:auction_id]
    if auction.cancel!
      redirect_to auction, notice: 'Auction cancelled'
    else
      redirect_to auction, alert: 'Can\'t cancel the auction'
    end
  end
end

app/controllers/publishings_controller.rb
class PublishingsController < ApplicationController
  def create
    auction = Auction.find params[:auction_id]
    if auction.publish!
      redirect_to auction, notice: 'Auction published'
    else
      redirect_to auction, alert: 'Can\'t publish the auction'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by email: params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Logged in'
    else
      flash[:alert] = 'Wrong email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/controllers/transitions_controller.rb
class TransitionsController < ApplicationController
  before_action :find_auction

  def create_draft
    if @auction.draft!
      redirect_to @auction, notice: 'Auction is now a draft'
    else
      redirect_to @auction, alert: 'Can\'t do this. Sorry.'
    end
  end

  def create_cancel
    if @auction.cancel!
      redirect_to @auction, notice: 'Auction is cancelled'
    else
      redirect_to @auction, alert: 'Can\'t do this. Sorry.'
    end
  end

  def create_publish
    if @auction.publish!
      redirect_to @auction, notice: 'Auction published'
    else
      redirect_to @auction, alert: 'Can\'t do this. Sorry.'
    end
  end

  def create_met
    if @auction.met!
      redirect_to @auction, notice: 'Auction reserve price has been met'
    else
      redirect_to @auction, alert: 'Can\'t do this. Sorry.'
    end
  end

  def create_not_met
    if @auction.not_met!
      redirect_to @auction, notice: 'Auction reserve price not met'
    else
      redirect_to @auction, alert: 'Can\'t do this. Sorry.'
    end
  end

  private

  def find_auction
    @auction = Auction.find params[:auction_id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Logged In!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/cancels_helper.rb
module CancelsHelper
end

app/helpers/publishings_helper.rb
module PublishingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transitions_helper.rb
module TransitionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/_auction_form.html.erb
<% if @auction.errors.any? %>
  <ul>
    <% @auction.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for @auction do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_area :details, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :date_ending %>
    <%= f.text_field :date_ending, class: 'form-control datepicker' %>
  </div>
  <div class="form-group">
    <%= f.label :reserve_price %>
    <%= f.text_field :reserve_price, class: 'form-control' %>
  </div>
  <%= f.submit btn_label, class: "btn btn-primary" %>
<% end %>

app/views/auctions/edit.html.erb
<h1>Edit Auction</h1>
<%= render 'auction_form', btn_label: 'Edit auction' %>

app/views/auctions/index.html.erb
<h1>All the Auctions</h1>
<table class="table table-striped">
  <tr>
    <th>Auction</th>
    <th>Details</th>
    <th>Reserve</th>
    <th>Status</th>
    <th>End Date</th>
  </tr>

<% @auctions.each do |a| %>
  <tr>
    <td class="text-nowrap"><%= link_to a.title, a %></td>
    <td><%= a.details %></td>
    <td><%= a.reserve_price %></td>
    <td><%= a.aasm_state %></td>
    <td class="text-nowrap"><%= a.date_ending %></td>
  </tr>
<% end %>
</table>

app/views/auctions/new.html.erb
<h1>Add new auction</h1>

<%= render 'auction_form', btn_label: 'New auction' %>

app/views/auctions/show.html.erb
<h1><%= @auction.title %></h1>

<div class="meta-data">
  <span><%= link_to '< Back to all auctions', root_path %></span>
  <span>Reserve Price: <%= @auction.reserve_price %></span>
  <span>End date: <%= @auction.date_ending %></span>
  <span>Status: <%= @auction.aasm_state %></span>
  <span><%= link_to 'Edit', edit_auction_path(@auction) %></span>
  <span><%= link_to 'Delete',
    auction_path(@auction),
    method: :delete
  %></span>
</div>

<h2>Details</h2>

<p><%= @auction.details %></p>

<% if @auction.draft? %>
    <%= link_to 'Publish',
      publish_path(@auction),
      method: :post,
      class: 'btn btn-primary'
    %>&nbsp;
    &nbsp;<%= link_to 'Cancel',
      cancel_path(@auction),
      method: :post
    %>
<% elsif @auction.published? %>
    <%= link_to 'Make Draft',
      draft_path(@auction),
      method: :post
    %>&nbsp;
    &nbsp;<%= link_to 'Cancel',
      cancel_path(@auction),
      method: :post
    %>
<% elsif @auction.cancelled? %>
    <%= link_to 'Make Draft',
      draft_path(@auction),
      method: :post,
      class: 'btn btn-primary'
    %>
<% end %>

<hr />

<h2>Current Bid:
  <% if @auction.bids.present? %>
    <%= number_to_currency(@auction.max_amount) %>
  <% else %>
    0
  <% end %>
</h2>

<h2>New Bid</h2>
<%= form_for [@auction, @bid] do |f| %>
  <%= f.text_field :amount, placeholder: '$' %>
  <%= f.submit 'Bid!', class: "btn btn-primary" %>
<% end %>

<h2>Bid History</h2>

<% @bids.each do |b| %>
  <%= number_to_currency(b.amount) %><br />
  <%= b.user.full_name %>&mdash;<%= b.created_at.strftime("%l:%M%P, %B %d, %Y ") %>
  <hr />
<% end %>

app/views/bids/index.html.erb
<h1>All my bids</h1>

<% @bids.each do |b| %>
<%= b.auction.title %>: <%= number_to_currency(b.amount) %>: <%= b.created_at.strftime("%l:%M%P, %B %d, %Y ") %>
<hr />
<% end %>

app/views/users/_signup_form.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit btn_label, class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'signup_form', btn_label: 'Sign up' %>