config/routes.rb
Rails.application.routes.draw do
  root 'auctions#index'
  post '/auctions/:auction_id/publish', to: 'transitions#create_publish', as: 'publish'
  post '/auctions/:auction_id/cancel', to: 'transitions#create_cancel', as: 'cancel'
  post '/auctions/:auction_id/met', to: 'transitions#create_met', as: 'met'
  post '/auctions/:auction_id/not-met', to: 'transitions#create_not_met', as: 'not_met'
  post '/auctions/:auction_id/win', to: 'transitions#create_win', as: 'win'
  post '/auctions/:auction_id/draft', to: 'transitions#create_draft', as: 'draft'

  resources :users, only: [:new, :create] do
    resources :bids, only: :index
  end
  resources :auctions, shallow: true do
    resources :bids
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  belongs_to :user
  has_many :bids, dependent: :destroy

  validates :title, presence: true
  validates :details, presence: true
  validates :date_ending, presence: true
  validates :reserve_price, presence: true

  include AASM

  aasm do
    state :draft, initial: true
    state :published
    state :reserve_met
    state :won
    state :cancelled
    state :reserve_not_met

    event :publish do
      transitions from: :draft, to: :published
    end

    event :met do
      transitions from: :published, to: :reserve_met
    end

    event :not_met do
      transitions from: :published, to: :reserve_not_met
    end

    event :win do
      transitions from: [:published, :reserve_met], to: :won
    end

    event :cancel do
      transitions from: [:draft, :published, :won], to: :cancelled
    end

    event :draft do
      transitions from: [:cancelled, :published], to: :draft
    end
  end

  def max_amount
    bids.max.amount
  end
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :auction
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :auctions, dependent: :nullify
  has_many :bids, dependent: :nullify

  before_validation :downcase_email

  validates :email, presence: true,
                    uniqueness: true,
                    format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def full_name
    "#{first_name} #{last_name}".strip.squeeze(' ').titleize
  end

  private

  def downcase_email
    email.downcase! if email.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user
    redirect_to new_session_path, notice: 'Please Log In.' unless user_signed_in?
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end
  helper_method :current_user
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :authenticate_user

  def index
    @auctions = Auction.order(title: :DESC)
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new auction_params
    @auction.user = current_user
    @auction.date_ending = params[:auction][:date_ending]
    if @auction.save
      redirect_to auction_path(@auction)
    else
      render :new
    end
  end

  def show
    @auction = Auction.find params[:id]
    @bid = Bid.new
    @bids = @auction.bids.order(amount: :DESC)
  end

  def edit
    @auction = Auction.find params[:id]
  end

  def update
    @auction = Auction.find params[:id]
    if @auction.update auction_params
      flash[:notice] = 'Auction updated'
      redirect_to @auction
    else
      flash.now[:alert] = 'Please see errors below!'
      render :edit
    end
  end

  def destroy
    @auction = Auction.find params[:id]
    @auction.destroy
    redirect_to auctions_path, notice: 'Auction deleted'
  end

  private

  def auction_params
    params.require(:auction).permit(:title, :details, :date_ending, :reserve_price)
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def index
    @bids = current_user.bids
  end

  def create
    @bids = Bid.order(amount: :DESC)
    @auction = Auction.find params[:auction_id]
    bid_params = params.require(:bid).permit(:amount)
    @bid = Bid.new bid_params
    @bid.user = current_user
    @bid.auction = @auction
    if @bid.save
      if @bid.amount > @auction.reserve_price
        if @auction.published? || @auction.reserve_not_met?
          @auction.update_attributes(aasm_state: 'reserve_met')
        elsif @auction.max_amount && @auction.date_ending > Time.current
          @auction.update_attributes(aasm_state: 'won')
        end
      end
      redirect_to auction_path(@auction)
    else
      render 'auctions/show'
    end
  end
end

app/controllers/cancels_controller.rb
class CancelsController < ApplicationController
  def create
    auction = Auction.find params[:auction_id]
    if auction.cancel!
      redirect_to auction, notice: 'Auction cancelled'
    else
      redirect_to auction, alert: 'Can\'t cancel the auction'
    end
  end
end

app/controllers/publishings_controller.rb
class PublishingsController < ApplicationController
  def create
    auction = Auction.find params[:auction_id]
    if auction.publish!
      redirect_to auction, notice: 'Auction published'
    else
      redirect_to auction, alert: 'Can\'t publish the auction'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by email: params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Logged in'
    else
      flash[:alert] = 'Wrong email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Logged In!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/cancels_helper.rb
module CancelsHelper
end

app/helpers/publishings_helper.rb
module PublishingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transitions_helper.rb
module TransitionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <div class="tagline">Making your bidding dreams come true.</div>
    <nav>
      <ul>
        <li><%= link_to "About", '#' %></li>
        <li><%= link_to "Contact", '#' %></li>
        <li><%= link_to "FAQ", '#' %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Bidddddr", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "New Auction", new_auction_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Hello, #{current_user.first_name}", root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= icon('cog') %>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "My Bids", user_bids_path(current_user) %></li>
              <li><%= link_to "Account Settings", '#' %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", sessions_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_session_path %></li>
          <li><%= link_to "Sign up", new_user_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bidddddr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application',
        'https://fonts.googleapis.com/css?family=Patua+One', media: 'all',
        'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    
  </body>
</html>